# Generated by Django 5.1.4 on 2025-01-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_authors_topics_delete_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
