# Generated by Django 5.1.4 on 2025-01-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_topics_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('heading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='page.topics')),
                ('liked', models.IntegerField()),
                ('disliked', models.IntegerField()),
                ('last_modified', models.DateTimeField()),
            ],
        ),
    ]
