# Generated by Django 5.1.4 on 2025-01-21 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField()),
                ('each_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.topics')),
            ],
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
