# Generated by Django 5.1.4 on 2025-01-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_comments_delete_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
