# Generated by Django 5.1.4 on 2025-01-22 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_remove_comments_dislikes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesDislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('each_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.topics')),
            ],
        ),
    ]
