# Generated by Django 5.1.4 on 2025-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_likesdislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesdislikes',
            name='dislike',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='likesdislikes',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
